---
# handlers file for basicSetup
- name: reload network
  command: "{{ item }}"
  ignore_errors: true
  with_items:
  - sysctl -p
  - systemctl restart networking

- name: reload systemd
  command: /bin/systemctl daemon-reload
